/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class game_of_life_GameOfLifeNativePacked */

#ifndef _Included_game_of_life_GameOfLifeNativePacked
#define _Included_game_of_life_GameOfLifeNativePacked
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     game_of_life_GameOfLifeNativePacked
 * Method:    getNGenerationNative
 * Signature: (I[[Z)V
 */
JNIEXPORT void JNICALL Java_game_1of_1life_GameOfLifeNativePacked_getNGenerationNative
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
