/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class game_of_life_GameOfLifeLookup */

#ifndef _Included_game_of_life_GameOfLifeLookup
#define _Included_game_of_life_GameOfLifeLookup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     game_of_life_GameOfLifeLookup
 * Method:    getNGenerationNative
 * Signature: ([CI[[Z)V
 */
JNIEXPORT void JNICALL Java_game_1of_1life_GameOfLifeLookup_getNGenerationNative
  (JNIEnv *, jobject, jcharArray, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
