/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class game_of_life_GameOfLifeMultithread */

#ifndef _Included_game_of_life_GameOfLifeMultithread
#define _Included_game_of_life_GameOfLifeMultithread
#ifdef __cplusplus
extern "C" {
#endif
#undef game_of_life_GameOfLifeMultithread_threadcount
#define game_of_life_GameOfLifeMultithread_threadcount 8L
/*
 * Class:     game_of_life_GameOfLifeMultithread
 * Method:    getNGenerationNative
 * Signature: (I[BI[[Z)V
 */
JNIEXPORT void JNICALL Java_game_1of_1life_GameOfLifeMultithread_getNGenerationNative
  (JNIEnv *, jobject, jint, jbyteArray, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
