/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class game_of_life_GameOfLifeNativeDirty */

#ifndef _Included_game_of_life_GameOfLifeNativeDirty
#define _Included_game_of_life_GameOfLifeNativeDirty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     game_of_life_GameOfLifeNativeDirty
 * Method:    getNGenerationNative
 * Signature: (I[[Z)V
 */
JNIEXPORT void JNICALL Java_game_1of_1life_GameOfLifeNativeDirty_getNGenerationNative
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
